#Este es el .ui pasado a python
#osea, cada cabio que se haga se va a reflejar aca pero en el archivo main no se vera afectado
# Form implementation generated from reading ui file 'Inicio.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 295)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(216, 220, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.Usuario = QtWidgets.QLabel(parent=self.frame)
        self.Usuario.setGeometry(QtCore.QRect(220, 120, 61, 21))
        self.Usuario.setStyleSheet("background-color: rgb(216, 220, 255);")
        self.Usuario.setObjectName("Usuario")
        self.Contra = QtWidgets.QLabel(parent=self.frame)
        self.Contra.setGeometry(QtCore.QRect(210, 170, 91, 21))
        self.Contra.setObjectName("Contra")
        self.textEdit = QtWidgets.QTextEdit(parent=self.frame)
        self.textEdit.setGeometry(QtCore.QRect(200, 140, 104, 21))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.frame)
        self.textEdit_2.setGeometry(QtCore.QRect(200, 190, 104, 21))
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.frame.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">puta verga</span></p></body></html>"))
        self.Usuario.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:72pt;\">Hola mundo</span></p></body></html>"))
        self.Usuario.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Usuario</span></p></body></html>"))
        self.Contra.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Contraseña</span></p></body></html>"))
